services:
  - type: web
    name: isidro-webapi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    port: 10000
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.13
